In [18]:
import re
import numpy as np
from numpy.linalg import solve

In [2]:
input_str = """Button A: X+94, Y+34
Button B: X+22, Y+67
Prize: X=8400, Y=5400

Button A: X+26, Y+66
Button B: X+67, Y+21
Prize: X=12748, Y=12176

Button A: X+17, Y+86
Button B: X+84, Y+37
Prize: X=7870, Y=6450

Button A: X+69, Y+23
Button B: X+27, Y+71
Prize: X=18641, Y=10279

Button A: X+29, Y+86
Button B: X+19, Y+16
Prize: X=2240, Y=2810"""

In [3]:
lines = input_str.split("\n\n")

results = []

for line in lines:
    a, b, c = line.split("\n")
    int_a = [int(x) for x in re.findall(r'\d+', a)]
    int_b = [int(x) for x in re.findall(r'\d+', b)]
    int_c = [int(x) for x in re.findall(r'\d+', c)]

    # Solve simultaneous equation
    left_side = np.array([[int_a[0], int_b[0]], [int_a[1], int_b[1]]])
    right_side = np.array([int_c[0], int_c[1]])
    results.append(np.linalg.inv(left_side).dot(right_side))



In [4]:
price = 0

for result in results:
    button_a = round(result[0], 3)
    button_b = round(result[1], 3)
    if button_a.is_integer() and button_b.is_integer():
        price += int(result[0]) * 3 + int(result[1])


In [5]:
price

617

In [6]:
results

[array([80., 40.]),
 array([141.40454076, 135.39525284]),
 array([38., 86.]),
 array([244.50163628,  65.56989247]),
 array([15., 95.])]

In [8]:
a = 15
b = 95

assert(29 * a + 19 * b == 2240)
assert(86 * a + 16 * b == 2810)

In [23]:
input_str = """Button A: X+29, Y+86
Button B: X+19, Y+16
Prize: X=2240, Y=2810"""

a, b, c = input_str.split("\n")

int_a = [int(x) for x in re.findall(r'(\d+)\D*(\d+)', a)[0]]
int_b = [int(x) for x in re.findall(r'(\d+)\D*(\d+)', b)[0]]
int_c = [int(x) for x in re.findall(r'(\d+)\D*(\d+)', c)[0]]


In [24]:
AB = np.column_stack((int_a, int_b))

In [25]:
AB

array([[29, 19],
       [86, 16]])

In [26]:
solution = np.rint(solve(AB, int_c))

In [27]:
solution

array([15., 95.])